const ATTR_TABLE = 'roles'
const ATTR_CHAR_DESCRIPTION = 'description'

const ATTR_INT_ID = 'id'
const ATTR_DATETIME_CREATED_AT = 'created_at'
const ATTR_DATETIME_UPDATED_AT = 'updated_at'
const ATTR_INT_CREATED_BY = 'created_by_id'
const ATTR_INT_UPDATED_BY = 'updated_by_id'
const ATTR_DATETIME_DELETED_AT = 'deleted_at'
const ATTR_CHAR_ENCRYPT = 'encryption_id'
const ATTR_INT_VERSION = 'version'

const ATTR_RELATION_UPDATED_BY = 'updated_by'
const ATTR_RELATION_CREATED_BY = 'created_by'
const ATTR_RELATION_MODULES = 'modules'
const ATTR_RELATION_ORGANIZATION = 'organization'

module.exports = {
    ATTR_TABLE,
    ATTR_CHAR_DESCRIPTION,
    ATTR_INT_ID,
    ATTR_DATETIME_CREATED_AT,
    ATTR_DATETIME_UPDATED_AT,
    ATTR_INT_CREATED_BY,
    ATTR_INT_UPDATED_BY,
    ATTR_DATETIME_DELETED_AT,
    ATTR_RELATION_UPDATED_BY,
    ATTR_RELATION_CREATED_BY,
    ATTR_RELATION_MODULES,
    ATTR_RELATION_ORGANIZATION,
    ATTR_CHAR_ENCRYPT,
    ATTR_INT_VERSION
};