const ATTR_TABLE = 'role_modules'
const ATTR_INT_ROLE = 'role_id'
const ATTR_INT_MODULE = 'module_id'

const ATTR_INT_ID = 'id'
const ATTR_DATETIME_CREATED_AT = 'created_at'
const ATTR_DATETIME_UPDATED_AT = 'updated_at'
const ATTR_INT_CREATED_BY = 'created_by_id'
const ATTR_INT_UPDATED_BY = 'updated_by_id'
const ATTR_DATETIME_DELETED_AT = 'deleted_at'
const ATTR_CHAR_ENCRYPT = 'encryption_id'

const ATTR_RELATION_UPDATED_BY = 'updated_by'
const ATTR_RELATION_CREATED_BY = 'created_by'
const ATTR_RELATION_ROLE = 'role'
const ATTR_RELATION_MODULE = 'module'

module.exports = {
  ATTR_CHAR_ENCRYPT,
  ATTR_DATETIME_CREATED_AT,
  ATTR_DATETIME_DELETED_AT,
  ATTR_DATETIME_UPDATED_AT,
  ATTR_INT_CREATED_BY,
  ATTR_INT_ID,
  ATTR_INT_MODULE,
  ATTR_INT_ROLE,
  ATTR_INT_UPDATED_BY,
  ATTR_RELATION_CREATED_BY,
  ATTR_RELATION_MODULE,
  ATTR_RELATION_ROLE,
  ATTR_RELATION_UPDATED_BY,
  ATTR_TABLE,
};
