const ATTR_TABLE = 'users'
const ATTR_CHAR_USERNAME = 'username'
const ATTR_CHAR_FIRSTNAME = 'firstname'
const ATTR_CHAR_LASTNAME = 'lastname'
const ATTR_CHAR_EMAIL = 'email'
const ATTR_CHAR_PASSWORD = 'password'
const ATTR_CHAR_MOBILE = 'mobile'
const ATTR_INT_WRONG_PASS = 'wrong_pass'
const ATTR_INT_STATUS = 'status'
const ATTR_CHAR_CONFIRMATION_CODE = 'confirmation_code'
const ATTR_DATETIME_LAST_REQUEST_TIME = 'last_request_time'
const ATTR_CHAR_REMEMBER_TOKEN = 'remember_token'
const ATTR_DATETIME_VERIFIED = 'verified_at'

const ATTR_INT_ID = 'id'
const ATTR_DATETIME_CREATED_AT = 'created_at'
const ATTR_DATETIME_UPDATED_AT = 'updated_at'
const ATTR_INT_CREATED_BY = 'created_by_id'
const ATTR_INT_UPDATED_BY = 'updated_by_id'
const ATTR_DATETIME_DELETED_AT = 'deleted_at'
const ATTR_CHAR_ENCRYPT = 'encryption_id'
const ATTR_INT_VERSION = 'version'

const ATTR_RELATION_UPDATED_BY = 'updated_by'
const ATTR_RELATION_CREATED_BY = 'created_by'
const ATTR_RELATION_ROLES = 'roles'

module.exports = {
  ATTR_TABLE,
  ATTR_CHAR_USERNAME,
  ATTR_CHAR_EMAIL,
  ATTR_CHAR_PASSWORD,
  ATTR_CHAR_MOBILE,
  ATTR_INT_WRONG_PASS,
  ATTR_INT_STATUS,
  ATTR_CHAR_CONFIRMATION_CODE,
  ATTR_CHAR_FIRSTNAME,
  ATTR_CHAR_LASTNAME,
  ATTR_DATETIME_LAST_REQUEST_TIME,
  ATTR_CHAR_REMEMBER_TOKEN,
  ATTR_DATETIME_VERIFIED,
  ATTR_INT_ID,
  ATTR_DATETIME_CREATED_AT,
  ATTR_DATETIME_UPDATED_AT,
  ATTR_INT_CREATED_BY,
  ATTR_INT_UPDATED_BY,
  ATTR_DATETIME_DELETED_AT,
  ATTR_RELATION_UPDATED_BY,
  ATTR_RELATION_CREATED_BY,
  ATTR_RELATION_ROLES,
  ATTR_CHAR_ENCRYPT,
  ATTR_INT_VERSION
};
